# Typos configuration
# Docs: https://github.com/crate-ci/typos

[default]
binary = false
extend-ignore-re = [
<< config(typos.ignore_re)|default(["vendor/.*"])|format('    "%s",')|join("\n") >>
]

[files]
extend-exclude = [
<< config(typos.exclude)|default([".git/","vendor/","node_modules/"])|format('    "%s",')|join("\n") >>
]
