name: PHPStan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------
      # Checkout source code
      # ------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      # ------------------------------------------------------------
      # Setup PHP (no Xdebug)
      # ------------------------------------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1  # v2.36.0
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      # ------------------------------------------------------------
      # Install dependencies
      # ------------------------------------------------------------
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # ------------------------------------------------------------
      # Check PHPStan config exists
      # ------------------------------------------------------------
      - name: Check PHPStan config exists
        id: phpstan
        run: |
          if [[ -f ".piqule/phpstan.neon" ]]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      # ------------------------------------------------------------
      # Run PHPStan
      # ------------------------------------------------------------
      - name: Run PHPStan
        if: steps.phpstan.outputs.run == 'true'
        run: composer phpstan

      - name: Skip PHPStan
        if: steps.phpstan.outputs.run == 'false'
        run: echo "Skipping PHPStan â€” no .piqule/phpstan.neon"
