# Typos configuration
# Docs: https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
    "vendor/.*",
]

[files]
extend-exclude = [
    ".git/",
    "vendor/",
    "node_modules/",
]

[check]
binary = false