name: Actionlint
on:
  workflow_call:
    inputs:
      fail_level:
        type: string
        required: false
        default: error
      reporter:
        type: string
        required: false
        default: github-check
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      # ------------------------------------------------------------
      # Run actionlint via reviewdog
      # ------------------------------------------------------------
      - name: Run actionlint
        uses: reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982  # v1.69.1
        with:
          fail_level: ${{ inputs.fail_level }}
          reporter: ${{ inputs.reporter }}
          level: error
