name: XML lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  xmllint:
    name: XML lint
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      # ------------------------------------------------------------
      # Install xmllint
      # ------------------------------------------------------------
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxml2-utils

      # ------------------------------------------------------------
      # Run XML lint
      # ------------------------------------------------------------
      - name: XML lint
        run: xmllint --noout .piqule/*/*.xml
