name: PR Size Checker
on:
  workflow_call:
    inputs:
      max_lines_changed:
        required: false
        type: number
        default: 250
permissions:
  contents: read
  pull-requests: read
jobs:
  pr_size:
    name: Check PR size
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # Checkout repository (full history required for diff)
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      # ------------------------------------------------------------
      # Run PR Size Checker
      # ------------------------------------------------------------
      - name: Run PR Size Checker
        uses: maidsafe/pr_size_checker@fa5820312a361f3f51aad2d3d9cb941d9e1d27db # v3
        with:
          max_lines_changed: ${{ inputs.max_lines_changed }}
