name: Release Drafter
on:
  workflow_call: {}
jobs:
  release_drafter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      # ------------------------------------------------------------
      # Update draft GitHub release based on merged pull requests
      # ------------------------------------------------------------
      - name: Update draft release
        uses: release-drafter/release-drafter@267d2e0268deae5d44f3ba5029dd4d6e85f9d52d  # v6.1.1
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
