name: XML lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  xmllint:
    name: XML lint
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      # ------------------------------------------------------------
      # Install xmllint
      # ------------------------------------------------------------
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxml2-utils

      # ------------------------------------------------------------
      # Run XML lint
      # ------------------------------------------------------------
      - name: XML lint
        run: xmllint --noout .piqule/*/*.xml
