name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  yamllint:
    name: YAML Lint
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_yamllint.yml
    with:
      config: .piqule/.yamllint.yml

  actionlint:
    name: Actionlint
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_actionlint.yml
    concurrency:
      group: ${{ github.workflow }}-actionlint-${{ github.ref }}
      cancel-in-progress: true

  markdownlint:
    name: Markdownlint
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_markdownlint.yml
    with:
      config: .piqule/.markdownlint-cli2.jsonc

  typos:
    name: Typos
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_typos.yml
    with:
      config: .piqule/_typos.toml

  php_cs_fixer:
    name: PHP-CS-Fixer
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_php-cs-fixer.yml
    with:
      config: .php-cs-fixer.php
      php-matrix: '["8.2","8.3","8.4","8.5"]'

  hadolint:
    name: Hadolint
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/_hadolint.yml
    with:
      dockerfile: Dockerfile
      config: .piqule/.hadolint.yml

  pr_size_checker:
    name: PR Size Checker
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_pr-size-checker.yml
    with:
      max_lines_changed: 250

  release_drafter:
    name: Release Drafter
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: read
    uses: ./.github/workflows/_release-drafter.yml
