name: Reusable PR Size Checker

on:
  workflow_call:
    inputs:
      max_lines_changed:
        required: false
        type: number
        default: 200

permissions:
  contents: read
  pull-requests: read

jobs:
  pr_size:
    name: Check PR size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run PR Size Checker
        uses: maidsafe/pr_size_checker@v2
        with:
          max_lines_changed: ${{ inputs.max_lines_changed }}