name: Typos

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
      - "**/*.php"
      - "typos/_typos.toml"
      - ".github/workflows/typos.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.md"
      - "**/*.php"
      - "typos/_typos.toml"
      - ".github/workflows/typos.yml"

permissions:
  contents: read

jobs:
  typos:
    uses: ./.github/workflows/typos-reusable.yml
    with:
      config: typos-ci/_typos.toml